---

- name: Add ppa repository for Oracle Java
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java

- name: Add Neo4j apt key
  apt_key: url=http://debian.neo4j.org/neotechnology.gpg.key state=present

- name: Add Neo4j repository
  apt_repository: repo="deb http://debian.neo4j.org/repo stable/" state=present update_cache=yes

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Neo4j and dependencies
  sudo: yes
  apt: name={{item}} state=latest update_cache=yes force=yes
  with_items:
    - python-urllib3
    - libpython-stdlib
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    - neo4j

- name: Set open fd soft and hard limit
  lineinfile: dest=/etc/security/limits.conf regexp="{{ item.regexp }}" line="{{ item.line }}" insertbefore="# End of file" state=present
  with_items:
    - { regexp: '^neo4j\s+soft', line: 'neo4j   soft    nofile  40000' }
    - { regexp: '^neo4j\s+hard', line: 'neo4j   hard    nofile  40000' }

- name: Configure Neo4j
  template: src=neo4j.conf dest=/etc/neo4j/neo4j.conf owner=neo4j group=adm mode=0644
  notify: Restart Neo4j

- name: Set username and password
  template: src=auth dest=/var/lib/neo4j/data/dbms/auth owner=neo4j group=adm mode=0644

- name: Ensure Neo4j is enabled and started
  service: name=neo4j enabled=yes state=started
